#!/bin/sh
### BEGIN INIT INFO
#
# Provides:      ddns
# Required-Start:       $local_fs  $remote_fs
# Required-Stop:        $local_fs  $remote_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    initscript
# Description:  This file should be used to construct scripts to be placed in /etc/init.d.
#
### END INIT INFO

## Fill in name of program here.
PROG="photos"
MSG_PREFIX=" *"
PROG_BASE="/data/app/$PROG"
PROG_PATH="$PROG_BASE/lib/main.js" #::# Not need, but sometimes helpful (if $PROG resides in /opt for example).
PROG_PID="$PROG_BASE/logs/$PROG.pid"
PROG_LOG="$PROG_BASE/logs/$PROG.log"
PROG_ARGS="10003 /data/movie $PROG_PID"
PROG_NODE="/data/app/nodejs/bin/node"

start() {
        $PROG_NODE $PROG_PATH $PROG_ARGS
        echo "$MSG_PREFIX $PROG started"
}

stop() {
       	echo "$MSG_PREFIX $PROG stopped"
}


case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|reload}" 1>&2
        exit 1
    ;;
esac
